version: '2'
services:
    geradorreferencias-app:
        image: geradorreferencias
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://geradorreferencias-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=geradorReferencias
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    geradorreferencias-mongodb:
        extends:
            file: mongodb.yml
            service: geradorreferencias-mongodb
